### ISSUE TITLE
JHipster Registry doesn't recognize microservices or gateway

### ISSUE THREAD

**Issue by keyz231** [jhipster/generator-jhipster-nodejs#265]
I have installed a microservice using the guide:

`npm install -g generator-jhipster-nodejs`

and my microservice works ( for example I've tried to go to localhost:8081/api/users)

I have downloaded the jhipster-registry from github and start with `mvwn`

Now my registry recognize only 👍 
![image](https://user-images.githubusercontent.com/75093380/155129558-0b81563c-780d-419b-8b4e-94f96c89297b.png)

But nothing about the microservice.

About microservice:

.yo-rc.json

`{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "applicationType": "microservice",
    "baseName": "microservice",
    "jhipsterVersion": "7.0.1",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1645529869157,
    "serverPort": "8081",
    "packageName": "com.jhipster.node",
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "oracle",
    "authenticationType": "jwt",
    "enableTranslation": false,
    "nativeLanguage": "it",
    "packageFolder": "com/jhipster/node",
    "jwtSecretKey": "Yjg1ZGExYWU2YjhiNjZhNDUwMTc5ZDUzNzhlMGFkOGY1MWUwODdmYWY0OWQ1NTVhZTc3N2U4NTU5N2M4MDg5Njg1YmY4NDQzMjc1NjIxYzg3ZDc3MDllMDdiZGFmNDE4ODBkYTVlMWIxZWFhYjdkNjBkYjNmOTc4NTczYzEyNWE=",
    "serviceDiscoveryType": false,
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "enableHibernateCache": true,
    "reactive": false,
    "languages": ["en", "fr"]
  }
}
`

server/src/client/config/application.yml

```
# ===================================================================
# Configuration.
#
# This configuration will be overridden by the BACKEND_ENV you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    appname: microservice
    instanceId: microservice:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'microservice'
  registry:
    password: admin
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NDhjNjk1NTM3NWRlNjc1NDMwZjllNWFiMmVlYjQ4NzViYzY4MmY5ZWY2MzZhMzNiMTYxYmNlYjJkMWYwNDk0NDBlNDYwZThjMmFmNzAyNTQyOWYxMDhkM2QxYTQ3ZDFjM2I5YWU4YWVjOGRhNDc3MWE5OTExMzUyMjI3MDlmZWM=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    from: microservice@localhost
  swagger:
    default-include-pattern: /api/.*
    title: microservice API
    description: microservice API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
    path: /api/v2/api-docs

cloud:
  config:
    uri: http://admin:${jhipster.registry.password}@localhost:8761/config
    # name of the config server's property source (file.yml) that we want to use
    name: microservice
    profile: prod # profile(s) of the property source
    label: master # toggle to switch to a different version of the configuration as stored in git
    # it can be set to any label, branch or commit of the configuration source Git repository
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

```

server/src/client/config/application-dev.yml

`# ===================================================================
# Configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

server:
  port: 8081

  mail:
    host: localhost
    port: 25
    username:
    password:

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  registry:
      password: admin
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: microservice@localhost
    base-url: http://127.0.0.1:8082
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
`

I have also tried with a gateway, but the result is the same. How can I set my microservice to the registry? Thank you
