### ISSUE TITLE
Support Keycloak docker image and configuration for oauth2

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#64]
It can be used for keycloack oauth2 integration

**Comment by amanganiello90** [comment]
@hadirsa , would you like to implement this feature?
You have to add the template, under the server generator, of [keycloak.yml](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/keycloak.yml.ejs) replacing the variables, and after update for oauth2 choose the [README.md](https://github.com/jhipster/generator-jhipster-nodejs/blob/feature/oauth2/generators/common/templates/README.md.ejs).
So, generate an app, and replace in the**server/src/config/application.yml**:

```
issuer-uri: http://localhost:9080/auth/realms/jhipster
registration:
          oidc:
            client-id: web_app
            client-secret: web_app
```

Remember to run the docker container with:
```
docker-compose -f src/main/docker/keycloak.yml up
```

And so in localhost:8081, running your full app, try to perform a login.
